### ISSUE TITLE
New EyeTracking Demo .dbproj files missing

### ISSUE THREAD

**Issue by tomdevelops** [DragonBones/Demos#7]
Would it be possible to upload the EyeTracking Demo?

so long
tom

**Comment by akdcl** [comment]
Hi, DragonBones Pro cannot edit this animation for the time being, it is converted from live2d, you can download it form [here](http://res.live2d.com/res/sample_data/shizuku/shizuku.zip) , and use [dragonbones toos dev branch](https://github.com/DragonBones/Tools/tree/dev) converted it to dragonbones format, and use it in [dragonbones runtime dev branch](https://github.com/DragonBones/DragonBonesJS/tree/dev).

**Comment by tomdevelops** [comment]
ok, thank you for the information, i'll try that out.
